<?xml version="1.0"?>
<!DOCTYPE enemies [
<!ELEMENT enemies (enemy+)>
    <!ELEMENT enemy (id, name, description, maxHealth, level, strength, dexterity, defense, droppedItems, yieldsExperience, yieldsGold)>
        <!ELEMENT id  (#PCDATA)>
        <!ELEMENT name  (#PCDATA)>
        <!ELEMENT description  (#PCDATA)>
        <!ELEMENT maxHealth  (#PCDATA)>
        <!ELEMENT level  (#PCDATA)>
        <!ELEMENT strength  (#PCDATA)>
        <!ELEMENT dexterity  (#PCDATA)>
        <!ELEMENT defense  (#PCDATA)>
        <!ELEMENT droppedItems  (item+)>
            <!ELEMENT item (itemId, dropChance)>
                <!ELEMENT dropChance (#PCDATA)>
        <!ELEMENT yieldsExperience (#PCDATA)>
        <!ELEMENT yieldsGold (#PCDATA)>

<!ELEMENT itemId (#PCDATA)>

]>
<enemies>
  <enemy>
    <id>0</id>
    <name>Rabbit</name> 
    <description>There is a cute bunny chewing on a carrot</description>
    <maxHealth>10</maxHealth>
    <level>0</level>
    <strength>1</strength>
    <dexterity>7</dexterity>
    <defense>1</defense>
    <droppedItems>
      <item>
        <itemId>0</itemId>
        <dropChance>0.5</dropChance>
      </item>
    </droppedItems>
    <yieldsExperience>20</yieldsExperience>
    <yieldsGold>0</yieldsGold>
  </enemy>
  <enemy>
    <id>1</id>
    <name>Deer</name>
    <description>A deer is having a grass snack</description>
    <maxHealth>20</maxHealth>
    <level>0</level>
    <strength>1</strength>
    <dexterity>6</dexterity>
    <defense>1</defense>
    <droppedItems>
      <item>
        <itemId>1</itemId>
        <dropChance>0.5</dropChance>
      </item>
    </droppedItems>
    <yieldsExperience>20</yieldsExperience>
    <yieldsGold>0</yieldsGold>
  </enemy>
  <enemy>
    <id>2</id>
    <name>Bear</name>
    <description>A bear is feasting on a honeycomb</description>
    <maxHealth>30</maxHealth>
    <level>1</level>
    <strength>6</strength>
    <dexterity>2</dexterity>
    <defense>4</defense>
    <droppedItems>
      <item>
        <itemId>2</itemId>
        <dropChance>0.5</dropChance>
      </item>
      <item>
        <itemId>3</itemId>
        <dropChance>0.1</dropChance>
      </item>
      <item>
        <itemId>7</itemId>
        <dropChance>0.1</dropChance>
      </item>
    </droppedItems>
    <yieldsExperience>30</yieldsExperience>
    <yieldsGold>0</yieldsGold>
  </enemy>
  <enemy>
    <id>3</id>
    <name>Wolf</name>
    <description>A wolf is lurking around</description>
    <maxHealth>20</maxHealth>
    <level>1</level>
    <strength>4</strength>
    <dexterity>6</dexterity>
    <defense>3</defense>
    <droppedItems>
      <item>
        <itemId>5</itemId>
        <dropChance>0.6</dropChance>
      </item>
      <item>
        <itemId>6</itemId>
        <dropChance>0.1</dropChance>
      </item>
    </droppedItems>
    <yieldsExperience>30</yieldsExperience>
    <yieldsGold>0</yieldsGold>
  </enemy>
  <enemy>
    <id>4</id>
    <name>Goblin</name>
    <description>A goblin is munching on a sheep carcass</description>
    <maxHealth>40</maxHealth>
    <level>2</level>
    <strength>6</strength>
    <dexterity>6</dexterity>
    <defense>4</defense>
    <droppedItems>
      <item>
        <itemId>12</itemId>
        <dropChance>0.4</dropChance>
      </item>
      <item>
        <itemId>8</itemId>
        <dropChance>0.1</dropChance>
      </item>
      <item>
        <itemId>9</itemId>
        <dropChance>0.1</dropChance>
      </item>
    </droppedItems>
    <yieldsExperience>45</yieldsExperience>
    <yieldsGold>5</yieldsGold>
  </enemy>
  <enemy>
    <id>5</id>
    <name>Goblin archer</name>
    <description>A goblin archer is holding watch</description>
    <maxHealth>50</maxHealth>
    <level>3</level>
    <strength>8</strength>
    <dexterity>8</dexterity>
    <defense>4</defense>
    <droppedItems>
      <item>
        <itemId>12</itemId>
        <dropChance>0.4</dropChance>
      </item>
      <item>
        <itemId>10</itemId>
        <dropChance>0.1</dropChance>
      </item>
      <item>
        <itemId>9</itemId>
        <dropChance>0.1</dropChance>
      </item>
    </droppedItems>
    <yieldsExperience>70</yieldsExperience>
    <yieldsGold>15</yieldsGold>
  </enemy>
  <enemy>
    <id>6</id>
    <name>Goblin warrior</name>
    <description>A goblin warrior is marching around</description>
    <maxHealth>70</maxHealth>
    <level>4</level>
    <strength>9</strength>
    <dexterity>5</dexterity>
    <defense>9</defense>
    <droppedItems>
      <item>
        <itemId>12</itemId>
        <dropChance>0.4</dropChance>
      </item>
      <item>
        <itemId>11</itemId>
        <dropChance>0.1</dropChance>
      </item>
    </droppedItems>
    <yieldsExperience>100</yieldsExperience>
    <yieldsGold>35</yieldsGold>
  </enemy>
  <enemy>
    <id>7</id>
    <name>Orc</name>
    <description>An orc is sharpening his axe</description>
    <maxHealth>100</maxHealth>
    <level>5</level>
    <strength>11</strength>
    <dexterity>5</dexterity>
    <defense>9</defense>
    <droppedItems>
      <item>
        <itemId>12</itemId>
        <dropChance>0.4</dropChance>
      </item>
      <item>
        <itemId>16</itemId>
        <dropChance>0.1</dropChance>
      </item>
    </droppedItems>
    <yieldsExperience>100</yieldsExperience>
    <yieldsGold>35</yieldsGold>
  </enemy>
</enemies>