<?xml version="1.0"?>
<!DOCTYPE items [
<!ELEMENT items (item+)>
             
<!ELEMENT item (id, displayName, addedStrength*, addedDexterity*, addedDefense*, saturationValue*)>

<!ELEMENT id  (#PCDATA)> 
<!ELEMENT displayName  (#PCDATA)>

<!ELEMENT addedStrength  (#PCDATA)>
<!ELEMENT addedDexterity  (#PCDATA)>
<!ELEMENT addedDefense  (#PCDATA)>
<!ELEMENT saturationValue  (#PCDATA)>

<!ATTLIST item type (QUEST|BODYWEAR|HEADWEAR|LEGWEAR|WEAPON|FOOD) "QUEST">
]>

<items>
  <item type="FOOD">
    <id>0</id>
    <displayName>Rabbit meat</displayName> 
    <saturationValue>15</saturationValue>
  </item>
  <item type="FOOD">
    <id>1</id>
    <displayName>Deer meat</displayName>
    <saturationValue>20</saturationValue>
  </item>
  <item type="FOOD">
    <id>2</id>
    <displayName>Bear meat</displayName>
    <saturationValue>30</saturationValue>
  </item>
  <item type="FOOD">
    <id>3</id>
    <displayName>Honey</displayName>
    <saturationValue>20</saturationValue>
  </item>
  <item type="WEAPON">
    <id>4</id>
    <displayName>Spoon of Doom</displayName>
    <addedStrength>20</addedStrength>
    <addedDexterity>20</addedDexterity>
    <addedDefense>20</addedDefense>
  </item>
  <item type="FOOD">
    <id>5</id>
    <displayName>Wolf meat</displayName>
    <saturationValue>25</saturationValue>
  </item>
  <item type="WEAPON">
    <id>6</id>
    <displayName>Wolf tooth</displayName>
    <addedStrength>1</addedStrength>
    <addedDexterity>1</addedDexterity>
    <addedDefense>1</addedDefense>
  </item>
  <item type="WEAPON">
    <id>7</id>
    <displayName>Bear paw</displayName>
    <addedStrength>3</addedStrength>
    <addedDexterity>0</addedDexterity>
    <addedDefense>0</addedDefense>
  </item>
  <item type="WEAPON">
    <id>8</id>
    <displayName>Dagger</displayName>
    <addedStrength>3</addedStrength>
    <addedDexterity>2</addedDexterity>
    <addedDefense>1</addedDefense>
  </item>
  <item type="LEGWEAR">
    <id>9</id>
    <displayName>Leather leggings</displayName>
    <addedStrength>0</addedStrength>
    <addedDexterity>2</addedDexterity>
    <addedDefense>4</addedDefense>
  </item>
  <item type="HEADWEAR">
    <id>10</id>
    <displayName>Leather helmet</displayName>
    <addedStrength>0</addedStrength>
    <addedDexterity>2</addedDexterity>
    <addedDefense>4</addedDefense>
  </item>
  <item type="WEAPON">
    <id>11</id>
    <displayName>Short sword</displayName>
    <addedStrength>5</addedStrength>
    <addedDexterity>3</addedDexterity>
    <addedDefense>2</addedDefense>
  </item>
  <item type="FOOD">
    <id>12</id>
    <displayName>Rations</displayName>
    <saturationValue>30</saturationValue>
  </item>
  <item type="BODYWEAR">
    <id>13</id>
    <displayName>Leather chestplate</displayName>
    <addedStrength>0</addedStrength>
    <addedDexterity>2</addedDexterity>
    <addedDefense>4</addedDefense>
  </item>
  <item type="LEGWEAR">
    <id>14</id>
    <displayName>Leather boots</displayName>
    <addedStrength>0</addedStrength>
    <addedDexterity>2</addedDexterity>
    <addedDefense>4</addedDefense>
  </item>
  <item type="WEAPON">
    <id>15</id>
    <displayName>Fiddlestick</displayName>
    <addedStrength>-25</addedStrength>
    <addedDexterity>-25</addedDexterity>
    <addedDefense>-25</addedDefense>
  </item>
    <item type="WEAPON">
        <id>16</id>
        <displayName>Rusty axe</displayName>
        <addedStrength>7</addedStrength>
        <addedDexterity>2</addedDexterity>
        <addedDefense>4</addedDefense>
    </item>
</items>