<?xml version="1.0"?>
<!DOCTYPE shops [
<!ELEMENT shops (shop+)>
    <!ELEMENT shop (id, name, description, restockCost, storage)>
        <!ELEMENT id  (#PCDATA)>
        <!ELEMENT name  (#PCDATA)>
        <!ELEMENT description  (#PCDATA)>
        <!ELEMENT restockCost  (#PCDATA)>
        <!ELEMENT storage (item+)>
            <!ELEMENT item (itemId, availableChance)>
                <!ELEMENT itemId (#PCDATA)>
                <!ELEMENT availableChance (#PCDATA)>
]>

<shops>
  <shop>
    <id>0</id>
    <name>Starter shop</name>
    <description>A shop that is still open in this pandemic is nearby</description>
    <restockCost>50</restockCost>
    <storage>
      <item>
        <itemId>12</itemId>
        <availableChance>1</availableChance>
      </item>
      <item>
        <itemId>12</itemId>
        <availableChance>0.9</availableChance>
      </item>
      <item>
        <itemId>8</itemId>
        <availableChance>0.8</availableChance>
      </item>
      <item>
        <itemId>9</itemId>
        <availableChance>0.6</availableChance>
      </item>
      <item>
        <itemId>10</itemId>
        <availableChance>0.6</availableChance>
      </item>
      <item>
        <itemId>11</itemId>
        <availableChance>0.6</availableChance>
      </item>
      <item>
        <itemId>14</itemId>
        <availableChance>0.6</availableChance>
      </item>
      <item>
        <itemId>13</itemId>
        <availableChance>0.6</availableChance>
      </item>
    </storage>
  </shop>
</shops>